---
- name: gather information from routers
  hosts: cisco
  gather_facts: false

  tasks:
    - name: gather router facts
      cisco.ios.facts:

    - name: display version
      debug:
        msg: "The IOS version is: "

    - name: display serial number
      debug:
        msg: "The serial number is:"
